# Generated by Django 2.2.12 on 2020-11-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a title of solution', max_length=200)),
                ('description', models.TextField(help_text='Enter a description of solution', max_length=1000)),
            ],
        ),
    ]
