# Generated by Django 2.2.12 on 2020-11-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='full_description',
            field=models.TextField(blank=True, help_text='Enter a full description of job', max_length=3000, null=True),
        ),
    ]
