# Generated by Django 2.2.12 on 2020-11-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201112_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(help_text='Enter a description of vacancy', max_length=2000),
        ),
    ]
