# Generated by Django 2.2.12 on 2020-11-12 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201112_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='nice_to_have',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='requirement',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='title',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='responsibility',
            field=models.ForeignKey(help_text='Enter a responsibilities of vacancy', on_delete=django.db.models.deletion.CASCADE, to='main.Job'),
        ),
    ]
