# Generated by Django 2.2.12 on 2020-11-12 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201112_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='responsibility',
            new_name='vacancy',
        ),
    ]
