# Generated by Django 2.2.12 on 2020-11-12 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201112_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='vacancy',
            new_name='name_of_vacancy',
        ),
    ]
