# Generated by Django 2.2.12 on 2020-11-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201112_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='requirements',
            field=models.CharField(blank=True, help_text='Enter a title of vacancy', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='responsibility',
            field=models.CharField(blank=True, help_text='Enter a title of vacancy', max_length=300, null=True),
        ),
    ]
