# Generated by Django 2.2.12 on 2020-11-12 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201112_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='requirements',
            new_name='requirement',
        ),
    ]
