# Generated by Django 2.2.12 on 2020-11-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201112_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='responsibility_1',
            field=models.CharField(blank=True, help_text='Enter a title of vacancy', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibility_2',
            field=models.CharField(blank=True, help_text='Enter a title of vacancy', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibility_3',
            field=models.CharField(blank=True, help_text='Enter a title of vacancy', max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='Vacancy',
        ),
    ]
