# Generated by Django 2.2.12 on 2020-11-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20201112_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a full description of job', max_length=2000, null=True),
        ),
    ]
