# Generated by Django 2.2.12 on 2020-11-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='requirement_4',
            field=models.CharField(blank=True, help_text='Enter a requirement of vacancy', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='requirement_5',
            field=models.CharField(blank=True, help_text='Enter a requirement of vacancy', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='requirement_6',
            field=models.CharField(blank=True, help_text='Enter a requirement of vacancy', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='requirement_7',
            field=models.CharField(blank=True, help_text='Enter a requirement of vacancy', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='requirement_8',
            field=models.CharField(blank=True, help_text='Enter a requirement of vacancy', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='requirement_9',
            field=models.CharField(blank=True, help_text='Enter a requirement of vacancy', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibility_4',
            field=models.CharField(blank=True, help_text='Enter a responsibility of vacancy', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibility_5',
            field=models.CharField(blank=True, help_text='Enter a responsibility of vacancy', max_length=300, null=True),
        ),
    ]
